spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/like_service_db
    username: postgres
    password: postgres
    hikari:
      schema: like_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS like_schema
      connection-timeout: 10000

